{{- if .Values.gateway.controller.auth.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway-operator.fullname" . }}-controller-auth
  labels:
    {{- include "gateway-operator.componentLabels" (list . "controller" (dict)) | nindent 4 }}
type: Opaque
stringData:
  GATEWAY_GATEWAY__CONTROLLER_AUTH_BASIC_USERS_0_PASSWORD: {{ .Values.gateway.controller.auth.adminPassword | quote }}
{{- end }}
