{{- $router := .Values.gateway.router -}}
{{- $deployment := $router.deployment -}}
{{- if $deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway-operator.fullname" . }}-router
  labels:
    {{- include "gateway-operator.componentLabels" (list . "router" $deployment.labels) | nindent 4 }}
  {{- $annotations := merge (deepCopy (default (dict) .Values.commonAnnotations)) (default (dict) $deployment.annotations) }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "gateway-operator.componentSelectorLabels" (list . "router") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gateway-operator.componentSelectorLabels" (list . "router") | nindent 8 }}
        {{- with $deployment.podLabels }}
{{ toYaml . | indent 8 }}
        {{- end }}
      {{- if $deployment.podAnnotations }}
      annotations:
        {{- toYaml $deployment.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "gateway-operator.serviceAccountName" . }}
      {{- $globalPullSecrets := default (list) .Values.imagePullSecrets }}
      {{- $componentPullSecrets := default (list) $router.imagePullSecrets }}
      {{- $pullSecrets := concat $globalPullSecrets $componentPullSecrets }}
      {{- if $pullSecrets }}
      imagePullSecrets:
        {{- range $pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with $deployment.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deployment.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with $deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gateway-router
          image: "{{ $router.image.repository }}:{{ $router.image.tag }}"
          imagePullPolicy: {{ $router.image.pullPolicy }}
          {{- with $deployment.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: XDS_SERVER_HOST
              value: {{ default (printf "%s-controller" (include "gateway-operator.fullname" .)) $deployment.env.xdsServerHost | quote }}
            - name: XDS_SERVER_PORT
              value: {{ default (printf "%d" (int $.Values.gateway.controller.service.ports.xds)) $deployment.env.xdsServerPort | quote }}
            {{- range $deployment.extraEnv }}
            - {{- toYaml . | nindent 14 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ $router.service.ports.http }}
              protocol: TCP
            - name: https
              containerPort: {{ $router.service.ports.https }}
              protocol: TCP
            - name: admin
              containerPort: {{ $router.service.ports.admin }}
              protocol: TCP
          livenessProbe:
            {{- toYaml $deployment.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $deployment.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml ($deployment.resources | default dict) | nindent 12 }}
{{- end }}
