{{- $router := .Values.gateway.router -}}
{{- $service := $router.service -}}
{{- if $router.deployment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-operator.fullname" . }}-router
  labels:
    {{- include "gateway-operator.componentLabels" (list . "router" $service.labels) | nindent 4 }}
  {{- if $service.annotations }}
  annotations:
    {{- toYaml $service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ $service.type }}
  selector:
    {{- include "gateway-operator.componentSelectorLabels" (list . "router") | nindent 4 }}
  ports:
    - name: http
      port: {{ $service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ $service.ports.https }}
      targetPort: https
      protocol: TCP
    - name: admin
      port: {{ $service.ports.admin }}
      targetPort: admin
      protocol: TCP
{{- end }}
