{{- $policy := .Values.gateway.policyEngine -}}
{{- $service := $policy.service -}}
{{- $config := .Values.gateway.config -}}
{{- if $policy.deployment.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-operator.fullname" . }}-policy-engine
  labels:
    {{- include "gateway-operator.componentLabels" (list . "policy-engine" $service.labels) | nindent 4 }}
  {{- if $service.annotations }}
  annotations:
    {{- toYaml $service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ $service.type }}
  selector:
    {{- include "gateway-operator.componentSelectorLabels" (list . "policy-engine") | nindent 4 }}
  ports:
    - name: ext
      port: {{ $service.ports.ext }}
      targetPort: ext
      protocol: TCP
    {{- if $config.policy_engine.admin.enabled }}
    - name: admin
      port: {{ default 9002 $config.policy_engine.admin.port }}
      targetPort: admin
      protocol: TCP
    {{- end }}
{{- end }}
