# permissions for end users to edit apiconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gateway-operator
    app.kubernetes.io/managed-by: kustomize
  name: apiconfiguration-editor-role
rules:
- apiGroups:
  - api.api-platform.wso2.com
  resources:
  - apiconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.api-platform.wso2.com
  resources:
  - apiconfigurations/status
  verbs:
  - get
