# permissions for end users to view gatewayconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gateway-operator
    app.kubernetes.io/managed-by: kustomize
  name: gatewayconfiguration-viewer-role
rules:
- apiGroups:
  - api.api-platform.wso2.com
  resources:
  - gatewayconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.api-platform.wso2.com
  resources:
  - gatewayconfigurations/status
  verbs:
  - get
