server:
  hostname: "0.0.0.0"
  port: 8090
  # http_only: false

gate_client:
  hostname: "localhost"
  port: 9091
  scheme: "https"
  login_path: "/login"
  error_path: "/error"

security:
  cert_file: "repository/resources/security/server.cert"
  key_file: "repository/resources/security/server.key"

database:
  identity:
    type: "sqlite"
    path: "repository/database/thunderdb.db"
    options: "_journal_mode=WAL&_busy_timeout=5000"
    max_open_conns: 500
    max_idle_conns: 100
    conn_max_lifetime: 3600

  runtime:
    type: "sqlite"
    path: "repository/database/runtimedb.db"
    options: "_journal_mode=WAL&_busy_timeout=5000"
    max_open_conns: 500
    max_idle_conns: 100
    conn_max_lifetime: 3600

cache:
  disabled: false
  type: "inmemory"
  size: 1000
  ttl: 3600
  eviction_policy: "LRU"
  cleanup_interval: 300
  # properties:
  #   - name: "ApplicationByIDCache"
  #     disabled: false
  #     size: 1000
  #     ttl: 3600
  #     eviction_policy: "LRU"

oauth:
  jwt:
    issuer: "thunder"
    validity_period: 3600
  refresh_token:
    renew_on_grant: false
    validity_period: 86400

flow:
  graph_directory: "repository/resources/graphs/"
  authn:
    default_flow: "auth_flow_config_basic"

cors:
  allowed_origins:
    - "https://localhost:3000"
    - "https://localhost:9001"
    - "https://localhost:9091"

