{{- if not .Values.watchNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gateway-operator.fullname" . }}-manager-role
  labels:
    app.kubernetes.io/name: {{ include "gateway-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
{{ include "gateway-operator.rbacRules" . }}
{{- end }}
