apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gateway-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gateway-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      control-plane: controller-manager
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/gateway-values: {{ include (print $.Template.BasePath "/gateway-values-configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "gateway-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        control-plane: controller-manager
    spec:
      securityContext:
{{ include "gateway-operator.podSecurityContext" . | indent 8 }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: {{ include "gateway-operator.image" . | quote }}
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          {{ if .Values.debug.enabled }}
          # run under delve in headless mode for remote debugging
          command:
            - ./dlv
          args:
            - exec
            - ./manager
            - "--headless"
            - "--listen=:2345"
            - "--api-version=2"
            - "--accept-multiclient"
            - "--log"
            - --
            - --leader-elect
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=0
          {{ else }}
          command:
            - /manager
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=0
          {{ end }}
          {{ if .Values.debug.enabled }}
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
            allowPrivilegeEscalation: true
          {{ end }}
          {{ if not .Values.debug.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          {{ end }}
          resources:
{{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config/config.yaml
              subPath: config.yaml
            - name: gateway-values
              mountPath: /config/gateway_values.yaml
              subPath: gateway_values.yaml
      volumes:
        - name: config
          configMap:
            name: {{ include "gateway-operator.fullname" . }}-config
        - name: gateway-values
          configMap:
            name: {{ include "gateway-operator.fullname" . }}-gateway-values