apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-operator.fullname" . }}-gateway-values
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gateway-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  gateway_values.yaml: |
{{ toYaml .Values.gateway.values | indent 4 }}
