{{- if .Values.watchNamespaces }}
{{- $root := . }}
{{- range .Values.watchNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gateway-operator.fullname" $root }}-manager-rolebinding
  namespace: {{ . }}
  labels:
    app.kubernetes.io/name: {{ include "gateway-operator.name" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gateway-operator.fullname" $root }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ $root.Values.serviceAccount.name }}
  namespace: {{ $root.Release.Namespace }}
{{- end }}
{{- end }}
