apiVersion: v2
name: gateway
kubeVersion: ">=1.24.0-0"
description: Helm chart for deploying the Gateway Operator components
version: 0.0.1
appVersion: "0.1.0-SNAPSHOT"
type: application
home: https://github.com/Tharsanan1/apip-operator
sources:
  - https://github.com/Tharsanan1/apip-operator
keywords:
  - gateway
  - envoy
  - wso2
  - api-platform
maintainers:
  - name: apip-operator-maintainers
    email: noreply@example.com
