apiVersion: v2
name: gateway
kubeVersion: ">=1.24.0-0"
description: Helm chart for deploying the Gateway Operator components
version: 0.2.0
appVersion: "0.7.0-SNAPSHOT"
type: application
home: https://github.com/wso2/api-platform
sources:
  - https://github.com/wso2/api-platform
keywords:
  - gateway
  - envoy
  - wso2
  - api-platform
maintainers:
  - name: ap-gateway-operator-maintainers
    email: contact@wso2.com
