apiVersion: v2
name: api-platform-gateway
kubeVersion: ">=1.24.0-0"
description: Helm chart for deploying the Gateway Operator (previously Open Choreo Gateway) components
version: 0.1.1
appVersion: "0.1.1"
type: application
home: https://github.com/Tharsanan1/apip-operator
sources:
  - https://github.com/Tharsanan1/apip-operator
keywords:
  - gateway
  - envoy
  - wso2
  - api-platform
maintainers:
  - name: apip-operator-maintainers
    email: noreply@example.com
