apiVersion: v1
kind: Service
metadata:
  name: secure-backend
  labels:
    app: secure-backend
spec:
  type: ClusterIP
  ports:
    - port: 5443
      targetPort: 5443
      protocol: TCP
  selector:
    app: secure-backend