apiVersion: gateway.api-platform.wso2.com/v1alpha1
kind: RestApi
metadata:
  labels:
    app.kubernetes.io/name: gateway-operator
    app.kubernetes.io/managed-by: kustomize
  name: restapi-sample
spec:
  # TODO(user): Add fields here
