name: Gateway Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.1.0)'
        required: true
        type: string

env:
  DOCKER_REGISTRY: ghcr.io/wso2/api-platform

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        run: |
          VERSION=${{ inputs.version }}
          make version-set COMPONENT=gateway VERSION_ARG=${VERSION}
          make update-images COMPONENT=gateway VERSION_ARG=${VERSION}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container


      - name: Run tests
        run: make test-gateway

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.API_PLATFORM_BOT_TOKEN }}

      - name: Build and push multi arch Docker images
        run: make build-and-push-gateway-multiarch

      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Release gateway version ${{ inputs.version }}"
          git tag -a gateway-v${{ inputs.version }} -m "Gateway ${{ inputs.version }}"
          git push origin gateway-v${{ inputs.version }}


      - name: Set to next dev version
        run: |
          make version-bump-next-dev COMPONENT=gateway
          make update-images COMPONENT=gateway VERSION_ARG=$(cat gateway/VERSION)
          git commit -am "Bump gateway to next dev version"
          git push origin main
